# Generated by Django 4.1.4 on 2022-12-20 12:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='n/a', max_length=50)),
                ('last_name', models.CharField(default='n/a', max_length=50)),
                ('phone_number', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('orders', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=[], null=True), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.IntegerField(unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('food_name', models.CharField(default='n/a', max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
