# Generated by Django 4.1.4 on 2022-12-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fid',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
