# Generated by Django 4.1.4 on 2022-12-22 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_product', '0002_food'),
        ('customers', '0002_alter_order_fid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customers'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='fid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_product.food'),
        ),
    ]
