# Generated by Django 4.1.4 on 2022-12-26 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_address_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customers'),
        ),
    ]
