# Generated by Django 4.1.4 on 2022-12-28 12:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_fortest'),
    ]

    operations = [
        migrations.AddField(
            model_name='fortest',
            name='quantity',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=[], max_length=50), null=True, size=None),
        ),
    ]
