# Generated by Django 4.1.4 on 2022-12-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(default='n/a', max_length=50, null=True)),
                ('price_data', models.IntegerField(default=0, null=True)),
                ('category', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Meal', 'Meal'), ('Dinner', 'Dinner'), ('FastFood', 'FastFood'), ('Dessert', 'Dessert')], default='Breakfast', max_length=50)),
            ],
        ),
    ]
